language: java
jdk:
  - oraclejdk8
before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
script: "travis_wait mvn test jacoco:report coveralls:report -Dgpg.skip"
notifications:
  slack: codarama:YVl3XmRANEPWD74rdOErjXGG
